package exception;

public class FinallyTest2 {
	
	public static void main(String[] args) {
		/*
		try {
			return;
		} finally {
			System.out.println("Finally");
		}
		*/
		/*
		try 
		{ 
		    int x = 0; 
		    int y = 5 / x; 
		} 
		catch (Exception e) {
		    System.out.println("Exception"); 
		} 
		catch (ArithmeticException ae){
		    System.out.println(" Arithmetic Exception"); 
		}
		System.out.println("finished");
		*/
	}
	
}
